version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /Users/delphine/docker/rabbit/volumes/data:/var/lib/rabbitmq/
      - /Users/delphine/docker/rabbit/volumes/logs:/var/log/rabbitmq/
